version: "3.7"

services:
 db:
    image: postgres:15
    container_name: db_fs
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

 app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-non-dev
    container_name: app_fs
    command: python src/main.py
    ports:
      - "5000:5000"
    depends_on:
      - db
