version: "3.7"

services:
 db:
    image: postgres:15
    container_name: db_fs
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

 app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-non-dev
    container_name: app_fs
    command: ["/app_fs/docker/app.sh"]
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - /home/v:/app_fs/home/user
